import { defineConfig } from '@lingui/cli'
import { formatter } from '@lingui/format-po'

export default defineConfig({
  sourceLocale: 'en',
  // `en-XA` is listed so the Vite plugin compiles its translations; it is NOT set
  // as `pseudoLocale` because its msgstrs are generated by
  // scripts/generate-pseudo-catalog.mjs, which Lingui's pseudoLocale would override.
  locales: ['en', 'en-XA'],
  catalogs: [
    {
      path: '<rootDir>/src/shared/i18n/locales/{locale}',
      include: ['<rootDir>/src'],
      exclude: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
    },
  ],
  // Keep source-file references for translators but omit line numbers: the drift
  // gate (i18n:check) must react to string changes, not to unrelated code moving
  // lines around.
  format: formatter({ origins: true, lineNumbers: false }),
})
