export const ROOM_FLOOR_WIDTH_METERS = 6
export const ROOM_FLOOR_DEPTH_METERS = 6
export const ROOM_WALL_HEIGHT_METERS = 2.5

export const ROOM_HALF_WIDTH_METERS = ROOM_FLOOR_WIDTH_METERS / 2
export const ROOM_HALF_DEPTH_METERS = ROOM_FLOOR_DEPTH_METERS / 2
